# Generated by Django 3.0.3 on 2020-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.IntegerField(null=True)),
                ('sentence', models.TextField(null=True)),
                ('wikilabel', models.IntegerField(null=True)),
                ('crowdlabel', models.IntegerField(null=True)),
            ],
        ),
    ]
